/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-dtree.h"

uint16_t mlof_predict_pdr_dtree(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 24) {
        if (hop_count <= 6) {
            if (parent_drop_rate <= 0) {
                if (is_new <= 0) {
                    if (p_cpu <= 9) {
                        if (p_cpu <= 3) {
                            if (p_cpu <= 0) {
                                return 65241;
                            } else {
                                return 65076;
                            }
                        } else {
                            if (hop_count <= 1) {
                                return 65102;
                            } else {
                                return 64440;
                            }
                        }
                    } else {
                        if (drop_rate <= 2) {
                            if (hop_count <= 2) {
                                return 64489;
                            } else {
                                return 62895;
                            }
                        } else {
                            if (hop_count <= 3) {
                                return 60584;
                            } else {
                                return 32894;
                            }
                        }
                    }
                } else {
                    if (p_cpu <= 10) {
                        if (p_cpu <= 5) {
                            if (p_cpu <= 1) {
                                return 64364;
                            } else {
                                return 61948;
                            }
                        } else {
                            if (drop_rate <= 2) {
                                return 59454;
                            } else {
                                return 40942;
                            }
                        }
                    } else {
                        if (drop_rate <= 1) {
                            if (hop_count <= 2) {
                                return 60325;
                            } else {
                                return 46200;
                            }
                        } else {
                            if (hop_count <= 2) {
                                return 46746;
                            } else {
                                return 20057;
                            }
                        }
                    }
                }
            } else {
                if (is_new <= 0) {
                    if (hop_count <= 3) {
                        if (hop_count <= 1) {
                            if (p_cpu <= 22) {
                                return 63481;
                            } else {
                                return 59595;
                            }
                        } else {
                            if (parent_drop_rate <= 22) {
                                return 61045;
                            } else {
                                return 49816;
                            }
                        }
                    } else {
                        if (drop_rate <= 3) {
                            if (p_cpu <= 19) {
                                return 57628;
                            } else {
                                return 50955;
                            }
                        } else {
                            if (p_cpu <= 22) {
                                return 49321;
                            } else {
                                return 22746;
                            }
                        }
                    }
                } else {
                    if (hop_count <= 3) {
                        if (p_cpu <= 5) {
                            if (hop_count <= 1) {
                                return 63127;
                            } else {
                                return 58658;
                            }
                        } else {
                            if (drop_rate <= 2) {
                                return 55544;
                            } else {
                                return 46511;
                            }
                        }
                    } else {
                        if (drop_rate <= 0) {
                            if (p_cpu <= 20) {
                                return 45032;
                            } else {
                                return 35270;
                            }
                        } else {
                            if (drop_rate <= 4) {
                                return 34634;
                            } else {
                                return 26993;
                            }
                        }
                    }
                }
            }
        } else {
            if (parent_drop_rate <= 0) {
                if (p_cpu <= 15) {
                    if (p_cpu <= 10) {
                        if (is_new <= 0) {
                            if (p_cpu <= 5) {
                                return 65307;
                            } else {
                                return 64236;
                            }
                        } else {
                            if (p_cpu <= 7) {
                                return 55978;
                            } else {
                                return 65535;
                            }
                        }
                    } else {
                        if (hop_count <= 7) {
                            if (p_cpu <= 11) {
                                return 57444;
                            } else {
                                return 63376;
                            }
                        } else {
                            if (p_cpu <= 11) {
                                return 57962;
                            } else {
                                return 45585;
                            }
                        }
                    }
                } else {
                    if (is_new <= 0) {
                        if (hop_count <= 7) {
                            if (p_cpu <= 20) {
                                return 59321;
                            } else {
                                return 42373;
                            }
                        } else {
                            if (hop_count <= 8) {
                                return 40202;
                            } else {
                                return 26511;
                            }
                        }
                    } else {
                        if (drop_rate <= 4) {
                            if (p_cpu <= 21) {
                                return 24673;
                            } else {
                                return 20472;
                            }
                        } else {
                            return 11428;
                        }
                    }
                }
            } else {
                if (is_new <= 0) {
                    if (p_cpu <= 7) {
                        return 62598;
                    } else {
                        if (drop_rate <= 1) {
                            if (hop_count <= 18) {
                                return 34093;
                            } else {
                                return 48495;
                            }
                        } else {
                            if (drop_rate <= 6) {
                                return 28429;
                            } else {
                                return 21011;
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 0) {
                        if (p_cpu <= 13) {
                            if (hop_count <= 9) {
                                return 43979;
                            } else {
                                return 32608;
                            }
                        } else {
                            if (p_cpu <= 16) {
                                return 29445;
                            } else {
                                return 23328;
                            }
                        }
                    } else {
                        if (parent_drop_rate <= 1) {
                            if (drop_rate <= 7) {
                                return 29975;
                            } else {
                                return 16763;
                            }
                        } else {
                            if (drop_rate <= 17) {
                                return 16643;
                            } else {
                                return 9790;
                            }
                        }
                    }
                }
            }
        }
    } else {
        if (hop_count <= 4) {
            if (is_new <= 0) {
                if (p_cpu <= 40) {
                    if (hop_count <= 2) {
                        if (parent_drop_rate <= 6) {
                            if (drop_rate <= 9) {
                                return 63914;
                            } else {
                                return 56276;
                            }
                        } else {
                            if (parent_drop_rate <= 24) {
                                return 57579;
                            } else {
                                return 65089;
                            }
                        }
                    } else {
                        if (drop_rate <= 3) {
                            if (p_cpu <= 31) {
                                return 59151;
                            } else {
                                return 53297;
                            }
                        } else {
                            if (parent_drop_rate <= 10) {
                                return 39299;
                            } else {
                                return 54993;
                            }
                        }
                    }
                } else {
                    if (hop_count <= 2) {
                        return 62473;
                    } else {
                        if (parent_drop_rate <= 2) {
                            if (drop_rate <= 0) {
                                return 29703;
                            } else {
                                return 17973;
                            }
                        } else {
                            if (p_cpu <= 42) {
                                return 29678;
                            } else {
                                return 44900;
                            }
                        }
                    }
                }
            } else {
                if (hop_count <= 3) {
                    if (p_cpu <= 30) {
                        if (drop_rate <= 0) {
                            if (parent_drop_rate <= 1) {
                                return 46444;
                            } else {
                                return 56017;
                            }
                        } else {
                            if (parent_drop_rate <= 8) {
                                return 36224;
                            } else {
                                return 51810;
                            }
                        }
                    } else {
                        if (parent_drop_rate <= 8) {
                            if (drop_rate <= 0) {
                                return 38664;
                            } else {
                                return 19381;
                            }
                        } else {
                            if (p_cpu <= 40) {
                                return 40917;
                            } else {
                                return 51051;
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 1) {
                        if (p_cpu <= 30) {
                            if (parent_drop_rate <= 3) {
                                return 36888;
                            } else {
                                return 44540;
                            }
                        } else {
                            if (p_cpu <= 46) {
                                return 27589;
                            } else {
                                return 20141;
                            }
                        }
                    } else {
                        if (parent_drop_rate <= 0) {
                            if (p_cpu <= 28) {
                                return 13615;
                            } else {
                                return 6276;
                            }
                        } else {
                            if (drop_rate <= 16) {
                                return 22725;
                            } else {
                                return 9567;
                            }
                        }
                    }
                }
            }
        } else {
            if (drop_rate <= 1) {
                if (p_cpu <= 35) {
                    if (hop_count <= 6) {
                        if (is_new <= 0) {
                            if (parent_drop_rate <= 0) {
                                return 56814;
                            } else {
                                return 33229;
                            }
                        } else {
                            if (p_cpu <= 25) {
                                return 41405;
                            } else {
                                return 25062;
                            }
                        }
                    } else {
                        if (is_new <= 0) {
                            if (parent_drop_rate <= 1) {
                                return 32702;
                            } else {
                                return 25215;
                            }
                        } else {
                            if (p_cpu <= 33) {
                                return 23148;
                            } else {
                                return 18956;
                            }
                        }
                    }
                } else {
                    if (p_cpu <= 58) {
                        if (parent_drop_rate <= 6) {
                            if (hop_count <= 10) {
                                return 17423;
                            } else {
                                return 21807;
                            }
                        } else {
                            if (hop_count <= 30) {
                                return 22068;
                            } else {
                                return 34066;
                            }
                        }
                    } else {
                        if (is_new <= 0) {
                            if (p_cpu <= 72) {
                                return 12829;
                            } else {
                                return 7752;
                            }
                        } else {
                            if (hop_count <= 25) {
                                return 17871;
                            } else {
                                return 5825;
                            }
                        }
                    }
                }
            } else {
                if (p_cpu <= 46) {
                    if (hop_count <= 11) {
                        if (p_cpu <= 32) {
                            if (drop_rate <= 6) {
                                return 21791;
                            } else {
                                return 14882;
                            }
                        } else {
                            if (drop_rate <= 10) {
                                return 14002;
                            } else {
                                return 10358;
                            }
                        }
                    } else {
                        if (drop_rate <= 30) {
                            if (p_cpu <= 29) {
                                return 25292;
                            } else {
                                return 19152;
                            }
                        } else {
                            if (parent_drop_rate <= 12) {
                                return 16352;
                            } else {
                                return 10326;
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 6) {
                        if (parent_drop_rate <= 21) {
                            if (hop_count <= 12) {
                                return 10233;
                            } else {
                                return 13176;
                            }
                        } else {
                            if (p_cpu <= 64) {
                                return 28233;
                            } else {
                                return 9589;
                            }
                        }
                    } else {
                        if (p_cpu <= 69) {
                            if (is_new <= 0) {
                                return 6746;
                            } else {
                                return 10421;
                            }
                        } else {
                            if (hop_count <= 25) {
                                return 7464;
                            } else {
                                return 2170;
                            }
                        }
                    }
                }
            }
        }
    }
}
