/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-lgbm.h"

static int32_t mlof_predict_pdr_lgbm_tree0(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 25) {
        if (parent_drop_rate <= 0) {
            return 50997;
        } else {
            if (p_cpu <= 16) {
                return 49985;
            } else {
                return 48419;
            }
        }
    } else {
        if (p_cpu <= 35) {
            if (is_new <= 0) {
                return 48486;
            } else {
                return 46743;
            }
        } else {
            if (drop_rate <= 1) {
                return 46552;
            } else {
                return 45766;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree1(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 31) {
            if (is_new <= 0) {
                return 1307;
            } else {
                return 598;
            }
        } else {
            return -1761;
        }
    } else {
        if (p_cpu <= 18) {
            if (hop_count <= 7) {
                return 560;
            } else {
                return -1612;
            }
        } else {
            if (drop_rate <= 1) {
                return -2499;
            } else {
                return -3405;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree2(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 32) {
            if (drop_rate <= 0) {
                return 1136;
            } else {
                return 171;
            }
        } else {
            return -1652;
        }
    } else {
        if (p_cpu <= 17) {
            if (parent_drop_rate <= 0) {
                return 1018;
            } else {
                return -1179;
            }
        } else {
            if (drop_rate <= 1) {
                return -2237;
            } else {
                return -3076;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree3(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 25) {
        if (parent_drop_rate <= 0) {
            return 1035;
        } else {
            if (is_new <= 0) {
                return 161;
            } else {
                return -1126;
            }
        }
    } else {
        if (p_cpu <= 39) {
            if (is_new <= 0) {
                return -896;
            } else {
                return -2189;
            }
        } else {
            if (drop_rate <= 4) {
                return -2407;
            } else {
                return -2962;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree4(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 24) {
        if (parent_drop_rate <= 0) {
            return 932;
        } else {
            if (is_new <= 0) {
                return 236;
            } else {
                return -973;
            }
        }
    } else {
        if (p_cpu <= 33) {
            if (parent_drop_rate <= 0) {
                return 73;
            } else {
                return -1539;
            }
        } else {
            if (drop_rate <= 0) {
                return -1940;
            } else {
                return -2515;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree5(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 4) {
            if (is_new <= 0) {
                return 903;
            } else {
                return 420;
            }
        } else {
            if (is_new <= 0) {
                return 336;
            } else {
                return -1934;
            }
        }
    } else {
        if (drop_rate <= 0) {
            if (parent_drop_rate <= 0) {
                return -220;
            } else {
                return -1590;
            }
        } else {
            return -2259;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree6(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 31) {
            if (is_new <= 0) {
                return 802;
            } else {
                return 323;
            }
        } else {
            if (hop_count <= 3) {
                return 755;
            } else {
                return -1657;
            }
        }
    } else {
        if (p_cpu <= 17) {
            return -18;
        } else {
            if (p_cpu <= 46) {
                return -1531;
            } else {
                return -2053;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree7(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 23) {
        if (parent_drop_rate <= 0) {
            return 700;
        } else {
            if (is_new <= 0) {
                return 229;
            } else {
                return -739;
            }
        }
    } else {
        if (p_cpu <= 32) {
            if (is_new <= 0) {
                return -148;
            } else {
                return -1525;
            }
        } else {
            if (drop_rate <= 1) {
                return -1403;
            } else {
                return -1890;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree8(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 3) {
            return 665;
        } else {
            if (drop_rate <= 0) {
                return 410;
            } else {
                return -1302;
            }
        }
    } else {
        if (p_cpu <= 17) {
            if (drop_rate <= 0) {
                return 368;
            } else {
                return -1856;
            }
        } else {
            if (drop_rate <= 1) {
                return -1198;
            } else {
                return -1725;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree9(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 20) {
            if (p_cpu <= 9) {
                return 636;
            } else {
                return 441;
            }
        } else {
            if (hop_count <= 3) {
                return 560;
            } else {
                return -874;
            }
        }
    } else {
        if (p_cpu <= 13) {
            return 475;
        } else {
            if (drop_rate <= 4) {
                return -1123;
            } else {
                return -1615;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree10(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 22) {
        if (parent_drop_rate <= 1) {
            if (p_cpu <= 11) {
                return 565;
            } else {
                return 341;
            }
        } else {
            if (p_cpu <= 11) {
                return 471;
            } else {
                return -374;
            }
        }
    } else {
        if (p_cpu <= 37) {
            if (is_new <= 0) {
                return -180;
            } else {
                return -1132;
            }
        } else {
            return -1297;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree11(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (drop_rate <= 4) {
            return 481;
        } else {
            if (hop_count <= 2) {
                return 470;
            } else {
                return -1073;
            }
        }
    } else {
        if (p_cpu <= 17) {
            if (drop_rate <= 0) {
                return 300;
            } else {
                return -1615;
            }
        } else {
            if (drop_rate <= 4) {
                return -916;
            } else {
                return -1363;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree12(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (is_new <= 0) {
            return 464;
        } else {
            if (p_cpu <= 10) {
                return 443;
            } else {
                return -604;
            }
        }
    } else {
        if (p_cpu <= 13) {
            if (hop_count <= 8) {
                return 456;
            } else {
                return -979;
            }
        } else {
            if (drop_rate <= 0) {
                return -712;
            } else {
                return -1164;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree13(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (is_new <= 0) {
            return 415;
        } else {
            if (p_cpu <= 6) {
                return 472;
            } else {
                return -415;
            }
        }
    } else {
        if (p_cpu <= 22) {
            if (is_new <= 0) {
                return 303;
            } else {
                return -952;
            }
        } else {
            if (p_cpu <= 54) {
                return -795;
            } else {
                return -1150;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree14(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (drop_rate <= 1) {
            if (is_new <= 0) {
                return 377;
            } else {
                return 91;
            }
        } else {
            if (hop_count <= 2) {
                return 418;
            } else {
                return -1042;
            }
        }
    } else {
        if (drop_rate <= 8) {
            return -736;
        } else {
            if (hop_count <= 11) {
                return -1177;
            } else {
                return -906;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree15(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 2) {
            return 373;
        } else {
            if (drop_rate <= 0) {
                return 246;
            } else {
                return -629;
            }
        }
    } else {
        if (p_cpu <= 13) {
            if (hop_count <= 9) {
                return 402;
            } else {
                return -1167;
            }
        } else {
            if (p_cpu <= 29) {
                return -409;
            } else {
                return -790;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree16(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 2) {
            return 339;
        } else {
            if (is_new <= 0) {
                return 259;
            } else {
                return -311;
            }
        }
    } else {
        if (drop_rate <= 0) {
            if (hop_count <= 6) {
                return 126;
            } else {
                return -552;
            }
        } else {
            if (hop_count <= 5) {
                return -1255;
            } else {
                return -770;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree17(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (drop_rate <= 1) {
            if (p_cpu <= 40) {
                return 258;
            } else {
                return -599;
            }
        } else {
            if (hop_count <= 2) {
                return 295;
            } else {
                return -818;
            }
        }
    } else {
        if (p_cpu <= 61) {
            if (p_cpu <= 8) {
                return 776;
            } else {
                return -531;
            }
        } else {
            return -869;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree18(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (p_cpu <= 28) {
            if (drop_rate <= 2) {
                return 241;
            } else {
                return -151;
            }
        } else {
            if (hop_count <= 3) {
                return 595;
            } else {
                return -620;
            }
        }
    } else {
        if (p_cpu <= 57) {
            if (drop_rate <= 8) {
                return -386;
            } else {
                return -747;
            }
        } else {
            return -777;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree19(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 29) {
        if (hop_count <= 7) {
            if (drop_rate <= 1) {
                return 218;
            } else {
                return -196;
            }
        } else {
            if (drop_rate <= 7) {
                return -398;
            } else {
                return -1158;
            }
        }
    } else {
        if (hop_count <= 3) {
            return 455;
        } else {
            if (p_cpu <= 54) {
                return -443;
            } else {
                return -666;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree20(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 3) {
            if (parent_drop_rate <= 0) {
                return 192;
            } else {
                return 400;
            }
        } else {
            if (drop_rate <= 2) {
                return 54;
            } else {
                return -868;
            }
        }
    } else {
        if (p_cpu <= 11) {
            return 356;
        } else {
            if (drop_rate <= 0) {
                return -293;
            } else {
                return -550;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree21(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (is_new <= 0) {
            if (p_cpu <= 49) {
                return 198;
            } else {
                return -1086;
            }
        } else {
            if (p_cpu <= 10) {
                return 214;
            } else {
                return -581;
            }
        }
    } else {
        if (p_cpu <= 8) {
            return 785;
        } else {
            if (hop_count <= 12) {
                return -470;
            } else {
                return -245;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree22(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (drop_rate <= 0) {
            if (p_cpu <= 42) {
                return 158;
            } else {
                return -524;
            }
        } else {
            if (hop_count <= 2) {
                return 244;
            } else {
                return -556;
            }
        }
    } else {
        if (p_cpu <= 10) {
            return 477;
        } else {
            if (p_cpu <= 65) {
                return -331;
            } else {
                return -592;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree23(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 29) {
        if (hop_count <= 7) {
            if (is_new <= 0) {
                return 171;
            } else {
                return -78;
            }
        } else {
            if (hop_count <= 17) {
                return -409;
            } else {
                return 351;
            }
        }
    } else {
        if (hop_count <= 3) {
            return 428;
        } else {
            if (p_cpu <= 64) {
                return -297;
            } else {
                return -513;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree24(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 29) {
        if (hop_count <= 8) {
            if (drop_rate <= 4) {
                return 131;
            } else {
                return -239;
            }
        } else {
            if (hop_count <= 17) {
                return -484;
            } else {
                return 331;
            }
        }
    } else {
        if (hop_count <= 3) {
            return 409;
        } else {
            if (hop_count <= 11) {
                return -407;
            } else {
                return -164;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree25(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 2) {
            if (p_cpu <= 25) {
                return 146;
            } else {
                return 564;
            }
        } else {
            if (is_new <= 0) {
                return 84;
            } else {
                return -286;
            }
        }
    } else {
        if (p_cpu <= 10) {
            return 273;
        } else {
            if (drop_rate <= 8) {
                return -175;
            } else {
                return -447;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree26(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (is_new <= 0) {
            if (p_cpu <= 40) {
                return 125;
            } else {
                return -362;
            }
        } else {
            if (p_cpu <= 5) {
                return 278;
            } else {
                return -380;
            }
        }
    } else {
        if (p_cpu <= 64) {
            if (p_cpu <= 7) {
                return 744;
            } else {
                return -208;
            }
        } else {
            return -440;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree27(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (parent_drop_rate <= 0) {
            if (p_cpu <= 2) {
                return 170;
            } else {
                return 58;
            }
        } else {
            return 338;
        }
    } else {
        if (p_cpu <= 11) {
            if (hop_count <= 10) {
                return 147;
            } else {
                return -1075;
            }
        } else {
            if (drop_rate <= 7) {
                return -160;
            } else {
                return -374;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree28(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (parent_drop_rate <= 0) {
            if (drop_rate <= 16) {
                return 84;
            } else {
                return -392;
            }
        } else {
            return 293;
        }
    } else {
        if (is_new <= 0) {
            if (parent_drop_rate <= 1) {
                return 189;
            } else {
                return -268;
            }
        } else {
            if (parent_drop_rate <= 0) {
                return -659;
            } else {
                return -184;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree29(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (parent_drop_rate <= 0) {
            if (hop_count <= 1) {
                return 119;
            } else {
                return 43;
            }
        } else {
            return 264;
        }
    } else {
        if (is_new <= 0) {
            if (parent_drop_rate <= 1) {
                return 175;
            } else {
                return -227;
            }
        } else {
            if (parent_drop_rate <= 0) {
                return -628;
            } else {
                return -143;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree30(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (parent_drop_rate <= 0) {
            if (drop_rate <= 16) {
                return 70;
            } else {
                return -369;
            }
        } else {
            return 215;
        }
    } else {
        if (p_cpu <= 10) {
            if (hop_count <= 10) {
                return 137;
            } else {
                return -1730;
            }
        } else {
            if (drop_rate <= 4) {
                return -99;
            } else {
                return -265;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree31(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 46) {
        if (drop_rate <= 1) {
            return 64;
        } else {
            if (hop_count <= 1) {
                return 221;
            } else {
                return -205;
            }
        }
    } else {
        if (is_new <= 0) {
            if (p_cpu <= 60) {
                return -236;
            } else {
                return -673;
            }
        } else {
            if (hop_count <= 18) {
                return -100;
            } else {
                return -395;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree32(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (p_cpu <= 36) {
            if (p_cpu <= 2) {
                return 127;
            } else {
                return 36;
            }
        } else {
            return 659;
        }
    } else {
        if (p_cpu <= 10) {
            if (hop_count <= 10) {
                return 129;
            } else {
                return -1170;
            }
        } else {
            if (drop_rate <= 0) {
                return -63;
            } else {
                return -200;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree33(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (parent_drop_rate <= 0) {
            if (hop_count <= 1) {
                return 90;
            } else {
                return 19;
            }
        } else {
            return 226;
        }
    } else {
        if (is_new <= 0) {
            if (parent_drop_rate <= 1) {
                return 136;
            } else {
                return -175;
            }
        } else {
            if (parent_drop_rate <= 7) {
                return -296;
            } else {
                return -26;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree34(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 46) {
        if (is_new <= 0) {
            return 60;
        } else {
            if (p_cpu <= 3) {
                return 229;
            } else {
                return -175;
            }
        }
    } else {
        if (is_new <= 0) {
            if (p_cpu <= 60) {
                return -152;
            } else {
                return -596;
            }
        } else {
            if (drop_rate <= 66) {
                return -111;
            } else {
                return 1159;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree35(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 4) {
        if (is_new <= 0) {
            if (parent_drop_rate <= 4) {
                return 60;
            } else {
                return -95;
            }
        } else {
            if (hop_count <= 2) {
                return 115;
            } else {
                return -104;
            }
        }
    } else {
        if (hop_count <= 12) {
            if (hop_count <= 1) {
                return 157;
            } else {
                return -247;
            }
        } else {
            return 55;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree36(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 0) {
        if (p_cpu <= 54) {
            if (p_cpu <= 2) {
                return 100;
            } else {
                return 27;
            }
        } else {
            return -281;
        }
    } else {
        if (parent_drop_rate <= 0) {
            if (is_new <= 0) {
                return 65;
            } else {
                return -664;
            }
        } else {
            if (p_cpu <= 9) {
                return 443;
            } else {
                return -66;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree37(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (is_new <= 0) {
        if (p_cpu <= 49) {
            if (hop_count <= 17) {
                return 39;
            } else {
                return 752;
            }
        } else {
            if (hop_count <= 37) {
                return -345;
            } else {
                return 1523;
            }
        }
    } else {
        if (p_cpu <= 3) {
            return 199;
        } else {
            if (parent_drop_rate <= 0) {
                return -424;
            } else {
                return -62;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree38(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 2) {
        if (p_cpu <= 24) {
            if (parent_drop_rate <= 0) {
                return 32;
            } else {
                return 227;
            }
        } else {
            return 431;
        }
    } else {
        if (p_cpu <= 5) {
            if (p_cpu <= 1) {
                return 304;
            } else {
                return 89;
            }
        } else {
            if (hop_count <= 12) {
                return -68;
            } else {
                return 72;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree39(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 4) {
        if (p_cpu <= 65) {
            if (hop_count <= 28) {
                return 20;
            } else {
                return 751;
            }
        } else {
            if (hop_count <= 31) {
                return -201;
            } else {
                return -1140;
            }
        }
    } else {
        if (hop_count <= 1) {
            return 176;
        } else {
            if (parent_drop_rate <= 0) {
                return -647;
            } else {
                return -100;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree40(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 2) {
        if (parent_drop_rate <= 0) {
            return 33;
        } else {
            if (drop_rate <= 38) {
                return 207;
            } else {
                return 705;
            }
        }
    } else {
        if (drop_rate <= 22) {
            if (is_new <= 0) {
                return 16;
            } else {
                return -78;
            }
        } else {
            if (parent_drop_rate <= 0) {
                return -884;
            } else {
                return -162;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree41(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 4) {
        if (hop_count <= 8) {
            return 21;
        } else {
            if (parent_drop_rate <= 1) {
                return -424;
            } else {
                return -11;
            }
        }
    } else {
        if (parent_drop_rate <= 5) {
            if (hop_count <= 1) {
                return 89;
            } else {
                return -260;
            }
        } else {
            if (hop_count <= 2) {
                return 523;
            } else {
                return -48;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree42(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 5) {
        if (is_new <= 0) {
            return 29;
        } else {
            if (parent_drop_rate <= 0) {
                return 131;
            } else {
                return 490;
            }
        }
    } else {
        if (is_new <= 0) {
            if (p_cpu <= 60) {
                return 31;
            } else {
                return -496;
            }
        } else {
            if (parent_drop_rate <= 0) {
                return -387;
            } else {
                return -22;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree43(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 2) {
        if (p_cpu <= 25) {
            if (parent_drop_rate <= 0) {
                return 19;
            } else {
                return 157;
            }
        } else {
            return 406;
        }
    } else {
        if (p_cpu <= 5) {
            if (is_new <= 0) {
                return 44;
            } else {
                return 324;
            }
        } else {
            if (is_new <= 0) {
                return -6;
            } else {
                return -98;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree44(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 74) {
        if (hop_count <= 14) {
            if (drop_rate <= 0) {
                return 14;
            } else {
                return -82;
            }
        } else {
            if (p_cpu <= 26) {
                return -292;
            } else {
                return 216;
            }
        }
    } else {
        if (parent_drop_rate <= 3) {
            if (hop_count <= 24) {
                return 485;
            } else {
                return -1310;
            }
        } else {
            return -277;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree45(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (hop_count <= 49) {
        if (hop_count <= 39) {
            if (drop_rate <= 69) {
                return 5;
            } else {
                return 593;
            }
        } else {
            if (parent_drop_rate <= 9) {
                return 327;
            } else {
                return -842;
            }
        }
    } else {
        return 1845;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree46(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 22) {
        if (p_cpu <= 82) {
            return 10;
        } else {
            if (drop_rate <= 2) {
                return -704;
            } else {
                return -48;
            }
        }
    } else {
        if (p_cpu <= 41) {
            if (parent_drop_rate <= 20) {
                return -322;
            } else {
                return 733;
            }
        } else {
            if (p_cpu <= 42) {
                return 1015;
            } else {
                return -56;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree47(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 46) {
        if (hop_count <= 15) {
            if (drop_rate <= 8) {
                return 18;
            } else {
                return -125;
            }
        } else {
            if (drop_rate <= 16) {
                return 209;
            } else {
                return 1176;
            }
        }
    } else {
        if (is_new <= 0) {
            return -231;
        } else {
            if (drop_rate <= 66) {
                return -18;
            } else {
                return 932;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree48(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (drop_rate <= 22) {
        if (hop_count <= 12) {
            if (p_cpu <= 46) {
                return 8;
            } else {
                return -113;
            }
        } else {
            if (hop_count <= 20) {
                return 179;
            } else {
                return -110;
            }
        }
    } else {
        if (p_cpu <= 41) {
            if (hop_count <= 1) {
                return 186;
            } else {
                return -448;
            }
        } else {
            return -14;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree49(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    if (p_cpu <= 3) {
        if (is_new <= 0) {
            return 20;
        } else {
            if (hop_count <= 3) {
                return 115;
            } else {
                return 549;
            }
        }
    } else {
        if (is_new <= 0) {
            if (p_cpu <= 49) {
                return 27;
            } else {
                return -245;
            }
        } else {
            if (parent_drop_rate <= 1) {
                return -255;
            } else {
                return 12;
            }
        }
    }
}

uint16_t mlof_predict_pdr_lgbm(uint8_t is_new, uint8_t p_cpu, uint8_t drop_rate, uint8_t parent_drop_rate, uint8_t hop_count) {
    int32_t sum = 0;
    sum += mlof_predict_pdr_lgbm_tree0(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree1(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree2(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree3(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree4(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree5(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree6(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree7(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree8(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree9(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree10(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree11(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree12(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree13(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree14(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree15(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree16(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree17(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree18(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree19(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree20(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree21(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree22(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree23(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree24(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree25(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree26(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree27(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree28(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree29(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree30(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree31(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree32(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree33(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree34(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree35(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree36(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree37(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree38(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree39(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree40(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree41(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree42(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree43(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree44(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree45(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree46(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree47(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree48(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    sum += mlof_predict_pdr_lgbm_tree49(is_new, p_cpu, drop_rate, parent_drop_rate, hop_count);
    if (sum < 0) sum = 0;
    if (sum > 65535) sum = 65535;
    return (uint16_t)sum;
}
