/* Auto-generated by scripts/models/to_c.py (linear) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-svm.h"

uint16_t mlof_predict_pdr_svm(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count) {
    double result = 48146.985824774674 + -0.2209558489594031 * (double)parent_ppm + 9.721635778991118 * (double)parent_drop_rate + 0.4222405708632784 * (double)rssi + -25.40185434911942 * (double)hop_count + -10851.943919847088 * (double)is_new + -22.974658413284406 * (double)cpu + -313.30133840969376 * (double)p_cpu + -0.8124295747067599 * (double)etx + -0.31220034076450287 * (double)ppm + -21.784723211487925 * (double)drop_rate + 1096.5604649809243 * (double)nbr_count;
    if (result < 0.0) result = 0.0;
    if (result > 65535.0) result = 65535.0;
    return (uint16_t)result;
}
