/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-dtree.h"

uint16_t mlof_predict_pdr_dtree(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 28) {
            if (is_new <= 0) {
                if (hop_count <= 3) {
                    if (hop_count <= 2) {
                        if (p_cpu <= 16) {
                            if (hop_count <= 1) {
                                return 65079;
                            } else {
                                return 64612;
                            }
                        } else {
                            if (parent_ppm <= 29) {
                                return 60622;
                            } else {
                                return 63803;
                            }
                        }
                    } else {
                        if (parent_ppm <= 65) {
                            if (p_cpu <= 18) {
                                return 62318;
                            } else {
                                return 56262;
                            }
                        } else {
                            if (drop_rate <= 1) {
                                return 64134;
                            } else {
                                return 59118;
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 2) {
                        if (cpu <= 56) {
                            if (p_cpu <= 15) {
                                return 62960;
                            } else {
                                return 60232;
                            }
                        } else {
                            return 30421;
                        }
                    } else {
                        if (cpu <= 20) {
                            if (p_cpu <= 20) {
                                return 59519;
                            } else {
                                return 41858;
                            }
                        } else {
                            if (cpu <= 37) {
                                return 37277;
                            } else {
                                return 21011;
                            }
                        }
                    }
                }
            } else {
                if (hop_count <= 3) {
                    if (hop_count <= 2) {
                        if (hop_count <= 1) {
                            if (p_cpu <= 8) {
                                return 62816;
                            } else {
                                return 59992;
                            }
                        } else {
                            if (cpu <= 58) {
                                return 59481;
                            } else {
                                return 48835;
                            }
                        }
                    } else {
                        if (cpu <= 56) {
                            if (p_cpu <= 20) {
                                return 55750;
                            } else {
                                return 43112;
                            }
                        } else {
                            if (parent_ppm <= 102) {
                                return 21562;
                            } else {
                                return 45327;
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 1) {
                        if (p_cpu <= 18) {
                            if (cpu <= 67) {
                                return 52137;
                            } else {
                                return 27758;
                            }
                        } else {
                            if (parent_ppm <= 128) {
                                return 16387;
                            } else {
                                return 40626;
                            }
                        }
                    } else {
                        if (parent_ppm <= 182) {
                            if (p_cpu <= 10) {
                                return 45386;
                            } else {
                                return 14782;
                            }
                        } else {
                            if (drop_rate <= 6) {
                                return 38891;
                            } else {
                                return 29783;
                            }
                        }
                    }
                }
            }
        } else {
            if (is_new <= 0) {
                if (hop_count <= 3) {
                    if (cpu <= 62) {
                        if (hop_count <= 2) {
                            if (p_cpu <= 31) {
                                return 63092;
                            } else {
                                return 59056;
                            }
                        } else {
                            if (drop_rate <= 6) {
                                return 57292;
                            } else {
                                return 43551;
                            }
                        }
                    } else {
                        return 26980;
                    }
                } else {
                    if (parent_ppm <= 805) {
                        if (drop_rate <= 2) {
                            if (parent_ppm <= 244) {
                                return 35794;
                            } else {
                                return 49365;
                            }
                        } else {
                            if (cpu <= 67) {
                                return 36254;
                            } else {
                                return 8973;
                            }
                        }
                    } else {
                        if (p_cpu <= 42) {
                            return 18232;
                        } else {
                            return 6642;
                        }
                    }
                }
            } else {
                if (drop_rate <= 1) {
                    if (parent_ppm <= 227) {
                        if (hop_count <= 3) {
                            return 45300;
                        } else {
                            if (cpu <= 48) {
                                return 20129;
                            } else {
                                return 6056;
                            }
                        }
                    } else {
                        if (hop_count <= 3) {
                            if (parent_ppm <= 354) {
                                return 51986;
                            } else {
                                return 44238;
                            }
                        } else {
                            if (cpu <= 84) {
                                return 35153;
                            } else {
                                return 11964;
                            }
                        }
                    }
                } else {
                    if (parent_ppm <= 458) {
                        if (hop_count <= 3) {
                            if (parent_ppm <= 290) {
                                return 38335;
                            } else {
                                return 15261;
                            }
                        } else {
                            if (cpu <= 47) {
                                return 19356;
                            } else {
                                return 11719;
                            }
                        }
                    } else {
                        if (parent_ppm <= 506) {
                            return 46165;
                        } else {
                            if (parent_ppm <= 676) {
                                return 22491;
                            } else {
                                return 31072;
                            }
                        }
                    }
                }
            }
        }
    } else {
        if (p_cpu <= 28) {
            if (p_cpu <= 15) {
                if (hop_count <= 9) {
                    if (is_new <= 0) {
                        if (drop_rate <= 0) {
                            if (hop_count <= 6) {
                                return 59564;
                            } else {
                                return 50666;
                            }
                        } else {
                            if (hop_count <= 7) {
                                return 32765;
                            } else {
                                return 49795;
                            }
                        }
                    } else {
                        if (drop_rate <= 1) {
                            if (p_cpu <= 9) {
                                return 52466;
                            } else {
                                return 41538;
                            }
                        } else {
                            if (p_cpu <= 11) {
                                return 21107;
                            } else {
                                return 36506;
                            }
                        }
                    }
                } else {
                    if (is_new <= 0) {
                        if (hop_count <= 16) {
                            if (p_cpu <= 11) {
                                return 47097;
                            } else {
                                return 35025;
                            }
                        } else {
                            if (p_cpu <= 12) {
                                return 19478;
                            } else {
                                return 31852;
                            }
                        }
                    } else {
                        if (hop_count <= 15) {
                            if (cpu <= 67) {
                                return 31808;
                            } else {
                                return 12102;
                            }
                        } else {
                            if (parent_ppm <= 122) {
                                return 4551;
                            } else {
                                return 22439;
                            }
                        }
                    }
                }
            } else {
                if (drop_rate <= 0) {
                    if (hop_count <= 7) {
                        if (is_new <= 0) {
                            if (p_cpu <= 19) {
                                return 51522;
                            } else {
                                return 42358;
                            }
                        } else {
                            if (parent_ppm <= 160) {
                                return 20786;
                            } else {
                                return 37842;
                            }
                        }
                    } else {
                        if (hop_count <= 11) {
                            if (parent_ppm <= 168) {
                                return 24837;
                            } else {
                                return 31593;
                            }
                        } else {
                            if (cpu <= 21) {
                                return 27873;
                            } else {
                                return 19493;
                            }
                        }
                    }
                } else {
                    if (parent_ppm <= 222) {
                        if (parent_ppm <= 99) {
                            if (cpu <= 22) {
                                return 5614;
                            } else {
                                return 201;
                            }
                        } else {
                            if (cpu <= 59) {
                                return 15853;
                            } else {
                                return 5695;
                            }
                        }
                    } else {
                        if (cpu <= 1) {
                            if (p_cpu <= 21) {
                                return 52026;
                            } else {
                                return 29722;
                            }
                        } else {
                            if (cpu <= 51) {
                                return 23776;
                            } else {
                                return 15441;
                            }
                        }
                    }
                }
            }
        } else {
            if (drop_rate <= 2) {
                if (p_cpu <= 43) {
                    if (parent_ppm <= 205) {
                        if (cpu <= 23) {
                            if (p_cpu <= 35) {
                                return 25808;
                            } else {
                                return 18457;
                            }
                        } else {
                            if (hop_count <= 8) {
                                return 19372;
                            } else {
                                return 11546;
                            }
                        }
                    } else {
                        if (parent_ppm <= 561) {
                            if (cpu <= 30) {
                                return 28438;
                            } else {
                                return 22798;
                            }
                        } else {
                            if (hop_count <= 8) {
                                return 26258;
                            } else {
                                return 19226;
                            }
                        }
                    }
                } else {
                    if (parent_ppm <= 235) {
                        if (cpu <= 36) {
                            if (cpu <= 1) {
                                return 24841;
                            } else {
                                return 16313;
                            }
                        } else {
                            if (hop_count <= 10) {
                                return 8956;
                            } else {
                                return 13984;
                            }
                        }
                    } else {
                        if (p_cpu <= 62) {
                            if (parent_ppm <= 728) {
                                return 23308;
                            } else {
                                return 16530;
                            }
                        } else {
                            if (hop_count <= 20) {
                                return 18040;
                            } else {
                                return 8564;
                            }
                        }
                    }
                }
            } else {
                if (cpu <= 29) {
                    if (hop_count <= 7) {
                        if (parent_ppm <= 152) {
                            if (drop_rate <= 11) {
                                return 16423;
                            } else {
                                return 4174;
                            }
                        } else {
                            if (p_cpu <= 44) {
                                return 25891;
                            } else {
                                return 17951;
                            }
                        }
                    } else {
                        if (drop_rate <= 11) {
                            if (parent_ppm <= 233) {
                                return 8989;
                            } else {
                                return 17448;
                            }
                        } else {
                            if (cpu <= 12) {
                                return 13522;
                            } else {
                                return 10123;
                            }
                        }
                    }
                } else {
                    if (parent_ppm <= 283) {
                        if (parent_ppm <= 161) {
                            if (hop_count <= 6) {
                                return 11513;
                            } else {
                                return 4180;
                            }
                        } else {
                            if (hop_count <= 15) {
                                return 8424;
                            } else {
                                return 12955;
                            }
                        }
                    } else {
                        if (drop_rate <= 8) {
                            if (cpu <= 70) {
                                return 14929;
                            } else {
                                return 10154;
                            }
                        } else {
                            if (hop_count <= 7) {
                                return 14251;
                            } else {
                                return 10379;
                            }
                        }
                    }
                }
            }
        }
    }
}
