/* Auto-generated by scripts/models/to_c.py (linear) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-linear.h"

uint16_t mlof_predict_pdr_linear(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count) {
    double result = 47138.60427448211 + -0.7512005604500122 * (double)parent_ppm + 86.55585309747018 * (double)parent_drop_rate + 37.14178599847848 * (double)rssi + -19.319036843517445 * (double)hop_count + -4792.398325032073 * (double)is_new + -18.369330372295504 * (double)cpu + -242.42970921602335 * (double)p_cpu + -37.69089183361804 * (double)etx + -0.6171630952017524 * (double)ppm + 35.22736916252678 * (double)drop_rate + 1472.5428771542784 * (double)nbr_count;
    if (result < 0.0) result = 0.0;
    if (result > 65535.0) result = 65535.0;
    return (uint16_t)result;
}
