/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-dtree.h"

uint16_t mlof_predict_pdr_dtree(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count) {
    if (hop_count <= 3) {
        if (ppm <= 26) {
            if (ppm <= 2) {
                if (rssi <= -51) {
                    if (etx <= 180) {
                        if (etx <= 175) {
                            return 41199;
                        } else {
                            return 26207;
                        }
                    } else {
                        if (cpu <= 39) {
                            if (etx <= 243) {
                                if (parent_ppm <= 33) {
                                    return 47761;
                                } else {
                                    return 61920;
                                }
                            } else {
                                if (rssi <= -67) {
                                    return 40091;
                                } else {
                                    return 51065;
                                }
                            }
                        } else {
                            if (rssi <= -83) {
                                return 37401;
                            } else {
                                return 40826;
                            }
                        }
                    }
                } else {
                    if (is_new <= 0) {
                        if (cpu <= 4) {
                            if (nbr_count <= 7) {
                                return 60294;
                            } else {
                                return 50517;
                            }
                        } else {
                            if (cpu <= 28) {
                                return 63286;
                            } else {
                                if (cpu <= 60) {
                                    return 57547;
                                } else {
                                    return 58599;
                                }
                            }
                        }
                    } else {
                        return 44724;
                    }
                }
            } else {
                if (nbr_count <= 6) {
                    if (parent_ppm <= 29) {
                        if (p_cpu <= 1) {
                            if (cpu <= 0) {
                                return 39121;
                            } else {
                                if (etx <= 207) {
                                    return 56682;
                                } else {
                                    return 46783;
                                }
                            }
                        } else {
                            if (p_cpu <= 20) {
                                if (rssi <= -79) {
                                    return 46094;
                                } else {
                                    return 31795;
                                }
                            } else {
                                return 29184;
                            }
                        }
                    } else {
                        if (rssi <= -77) {
                            return 60358;
                        } else {
                            return 47203;
                        }
                    }
                } else {
                    if (etx <= 151) {
                        if (ppm <= 16) {
                            if (hop_count <= 0) {
                                if (cpu <= 3) {
                                    if (cpu <= 0) {
                                        return 33734;
                                    } else {
                                        if (ppm <= 15) {
                                            return 40390;
                                        } else {
                                            return 46629;
                                        }
                                    }
                                } else {
                                    if (ppm <= 9) {
                                        return 41923;
                                    } else {
                                        if (ppm <= 13) {
                                            return 20476;
                                        } else {
                                            return 34133;
                                        }
                                    }
                                }
                            } else {
                                if (cpu <= 4) {
                                    return 43452;
                                } else {
                                    return 50889;
                                }
                            }
                        } else {
                            if (cpu <= 1) {
                                if (ppm <= 20) {
                                    return 48257;
                                } else {
                                    return 44784;
                                }
                            } else {
                                return 49212;
                            }
                        }
                    } else {
                        if (cpu <= 2) {
                            if (rssi <= -94) {
                                return 40471;
                            } else {
                                if (ppm <= 8) {
                                    if (etx <= 252) {
                                        if (etx <= 226) {
                                            return 20954;
                                        } else {
                                            return 33142;
                                        }
                                    } else {
                                        if (ppm <= 6) {
                                            return 12281;
                                        } else {
                                            return 17294;
                                        }
                                    }
                                } else {
                                    if (nbr_count <= 7) {
                                        if (parent_ppm <= 24) {
                                            return 46478;
                                        } else {
                                            return 31825;
                                        }
                                    } else {
                                        if (etx <= 202) {
                                            return 17729;
                                        } else {
                                            return 27813;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (nbr_count <= 7) {
                                if (etx <= 178) {
                                    return 24748;
                                } else {
                                    if (parent_ppm <= 29) {
                                        if (parent_ppm <= 10) {
                                            return 58359;
                                        } else {
                                            return 50063;
                                        }
                                    } else {
                                        return 41770;
                                    }
                                }
                            } else {
                                if (parent_ppm <= 56) {
                                    if (p_cpu <= 1) {
                                        if (rssi <= -79) {
                                            return 51602;
                                        } else {
                                            return 37588;
                                        }
                                    } else {
                                        if (ppm <= 11) {
                                            return 23872;
                                        } else {
                                            return 36390;
                                        }
                                    }
                                } else {
                                    return 14375;
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (hop_count <= 2) {
                if (parent_ppm <= 1415) {
                    if (is_new <= 0) {
                        if (cpu <= 9) {
                            if (ppm <= 175) {
                                if (ppm <= 32) {
                                    if (p_cpu <= 2) {
                                        if (etx <= 167) {
                                            return 38657;
                                        } else {
                                            return 47543;
                                        }
                                    } else {
                                        return 60450;
                                    }
                                } else {
                                    if (ppm <= 98) {
                                        if (parent_ppm <= 72) {
                                            return 59004;
                                        } else {
                                            return 61477;
                                        }
                                    } else {
                                        if (parent_ppm <= 1135) {
                                            return 58957;
                                        } else {
                                            return 51526;
                                        }
                                    }
                                }
                            } else {
                                if (ppm <= 434) {
                                    if (nbr_count <= 7) {
                                        if (etx <= 272) {
                                            return 55089;
                                        } else {
                                            return 49694;
                                        }
                                    } else {
                                        if (parent_ppm <= 870) {
                                            return 58334;
                                        } else {
                                            return 48562;
                                        }
                                    }
                                } else {
                                    if (rssi <= -73) {
                                        if (rssi <= -83) {
                                            return 58855;
                                        } else {
                                            return 47275;
                                        }
                                    } else {
                                        if (ppm <= 825) {
                                            return 61285;
                                        } else {
                                            return 58765;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (etx <= 333) {
                                if (parent_ppm <= 1131) {
                                    if (ppm <= 481) {
                                        if (ppm <= 175) {
                                            return 60639;
                                        } else {
                                            return 59116;
                                        }
                                    } else {
                                        if (etx <= 216) {
                                            return 61051;
                                        } else {
                                            return 58139;
                                        }
                                    }
                                } else {
                                    if (rssi <= -75) {
                                        return 49556;
                                    } else {
                                        if (etx <= 189) {
                                            return 53807;
                                        } else {
                                            return 60229;
                                        }
                                    }
                                }
                            } else {
                                if (etx <= 346) {
                                    return 34678;
                                } else {
                                    if (cpu <= 21) {
                                        return 50626;
                                    } else {
                                        return 59163;
                                    }
                                }
                            }
                        }
                    } else {
                        if (etx <= 161) {
                            if (ppm <= 727) {
                                if (ppm <= 150) {
                                    if (ppm <= 56) {
                                        return 56309;
                                    } else {
                                        if (cpu <= 38) {
                                            return 61340;
                                        } else {
                                            return 57102;
                                        }
                                    }
                                } else {
                                    if (cpu <= 3) {
                                        return 42490;
                                    } else {
                                        if (cpu <= 22) {
                                            return 57838;
                                        } else {
                                            return 54467;
                                        }
                                    }
                                }
                            } else {
                                if (ppm <= 1803) {
                                    if (drop_rate <= 8) {
                                        if (nbr_count <= 7) {
                                            return 62630;
                                        } else {
                                            return 56746;
                                        }
                                    } else {
                                        if (ppm <= 1134) {
                                            return 65535;
                                        } else {
                                            return 62974;
                                        }
                                    }
                                } else {
                                    if (ppm <= 2362) {
                                        return 57072;
                                    } else {
                                        return 62707;
                                    }
                                }
                            }
                        } else {
                            if (parent_ppm <= 22) {
                                if (etx <= 206) {
                                    if (ppm <= 711) {
                                        return 38971;
                                    } else {
                                        return 17880;
                                    }
                                } else {
                                    if (nbr_count <= 6) {
                                        return 56683;
                                    } else {
                                        if (ppm <= 273) {
                                            return 33085;
                                        } else {
                                            return 47624;
                                        }
                                    }
                                }
                            } else {
                                if (parent_ppm <= 161) {
                                    if (ppm <= 70) {
                                        if (cpu <= 1) {
                                            return 64141;
                                        } else {
                                            return 59763;
                                        }
                                    } else {
                                        if (parent_ppm <= 50) {
                                            return 51066;
                                        } else {
                                            return 56992;
                                        }
                                    }
                                } else {
                                    if (rssi <= -59) {
                                        if (ppm <= 124) {
                                            return 57522;
                                        } else {
                                            return 52208;
                                        }
                                    } else {
                                        if (hop_count <= 1) {
                                            return 52790;
                                        } else {
                                            return 41532;
                                        }
                                    }
                                }
                            }
                        }
                    }
                } else {
                    if (etx <= 319) {
                        if (rssi <= -58) {
                            if (nbr_count <= 5) {
                                if (parent_ppm <= 1703) {
                                    return 58709;
                                } else {
                                    return 55340;
                                }
                            } else {
                                if (ppm <= 380) {
                                    if (p_cpu <= 7) {
                                        if (parent_ppm <= 1711) {
                                            return 55370;
                                        } else {
                                            return 53026;
                                        }
                                    } else {
                                        if (etx <= 226) {
                                            return 48313;
                                        } else {
                                            return 38535;
                                        }
                                    }
                                } else {
                                    if (ppm <= 478) {
                                        return 56485;
                                    } else {
                                        if (rssi <= -77) {
                                            return 53678;
                                        } else {
                                            return 48024;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (parent_ppm <= 1715) {
                                if (rssi <= -51) {
                                    return 44979;
                                } else {
                                    return 58486;
                                }
                            } else {
                                return 18483;
                            }
                        }
                    } else {
                        if (hop_count <= 1) {
                            if (parent_ppm <= 1568) {
                                return 29765;
                            } else {
                                return 41608;
                            }
                        } else {
                            return 21250;
                        }
                    }
                }
            } else {
                if (ppm <= 753) {
                    if (ppm <= 127) {
                        if (etx <= 356) {
                            if (parent_ppm <= 563) {
                                if (rssi <= -71) {
                                    if (nbr_count <= 7) {
                                        if (parent_ppm <= 68) {
                                            return 65535;
                                        } else {
                                            return 62105;
                                        }
                                    } else {
                                        return 57638;
                                    }
                                } else {
                                    if (ppm <= 86) {
                                        if (parent_ppm <= 73) {
                                            return 51961;
                                        } else {
                                            return 61767;
                                        }
                                    } else {
                                        if (cpu <= 4) {
                                            return 43648;
                                        } else {
                                            return 61889;
                                        }
                                    }
                                }
                            } else {
                                if (p_cpu <= 12) {
                                    return 38375;
                                } else {
                                    return 57732;
                                }
                            }
                        } else {
                            return 39211;
                        }
                    } else {
                        if (parent_ppm <= 48) {
                            if (p_cpu <= 18) {
                                return 16254;
                            } else {
                                return 31439;
                            }
                        } else {
                            if (parent_ppm <= 428) {
                                if (parent_ppm <= 145) {
                                    if (rssi <= -64) {
                                        return 62941;
                                    } else {
                                        return 57087;
                                    }
                                } else {
                                    if (parent_ppm <= 231) {
                                        if (etx <= 237) {
                                            return 29855;
                                        } else {
                                            return 49323;
                                        }
                                    } else {
                                        if (ppm <= 171) {
                                            return 47468;
                                        } else {
                                            return 59274;
                                        }
                                    }
                                }
                            } else {
                                if (cpu <= 46) {
                                    if (rssi <= -48) {
                                        if (rssi <= -64) {
                                            return 48470;
                                        } else {
                                            return 18849;
                                        }
                                    } else {
                                        if (parent_ppm <= 555) {
                                            return 61616;
                                        } else {
                                            return 49751;
                                        }
                                    }
                                } else {
                                    return 25230;
                                }
                            }
                        }
                    }
                } else {
                    if (drop_rate <= 0) {
                        if (etx <= 202) {
                            return 47632;
                        } else {
                            if (etx <= 377) {
                                if (p_cpu <= 13) {
                                    return 11498;
                                } else {
                                    if (cpu <= 48) {
                                        return 42979;
                                    } else {
                                        return 23162;
                                    }
                                }
                            } else {
                                return 5642;
                            }
                        }
                    } else {
                        if (drop_rate <= 8) {
                            if (p_cpu <= 26) {
                                return 695;
                            } else {
                                return 9752;
                            }
                        } else {
                            return 19884;
                        }
                    }
                }
            }
        }
    } else {
        if (hop_count <= 5) {
            if (parent_drop_rate <= 0) {
                if (etx <= 319) {
                    if (ppm <= 258) {
                        if (nbr_count <= 6) {
                            if (cpu <= 45) {
                                if (parent_ppm <= 408) {
                                    if (hop_count <= 4) {
                                        if (parent_ppm <= 52) {
                                            return 46124;
                                        } else {
                                            return 60133;
                                        }
                                    } else {
                                        return 43624;
                                    }
                                } else {
                                    if (rssi <= -59) {
                                        return 49694;
                                    } else {
                                        return 27116;
                                    }
                                }
                            } else {
                                return 23757;
                            }
                        } else {
                            if (rssi <= -80) {
                                if (rssi <= -85) {
                                    return 19899;
                                } else {
                                    return 4761;
                                }
                            } else {
                                if (nbr_count <= 7) {
                                    if (parent_ppm <= 871) {
                                        if (parent_ppm <= 287) {
                                            return 21131;
                                        } else {
                                            return 43928;
                                        }
                                    } else {
                                        return 9593;
                                    }
                                } else {
                                    if (etx <= 205) {
                                        return 60961;
                                    } else {
                                        return 38829;
                                    }
                                }
                            }
                        }
                    } else {
                        if (p_cpu <= 49) {
                            if (p_cpu <= 10) {
                                if (ppm <= 933) {
                                    return 10853;
                                } else {
                                    return 104;
                                }
                            } else {
                                if (parent_ppm <= 253) {
                                    if (p_cpu <= 22) {
                                        return 27946;
                                    } else {
                                        return 5346;
                                    }
                                } else {
                                    if (nbr_count <= 6) {
                                        if (p_cpu <= 22) {
                                            return 32526;
                                        } else {
                                            return 14706;
                                        }
                                    } else {
                                        if (p_cpu <= 27) {
                                            return 30620;
                                        } else {
                                            return 48602;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (rssi <= -49) {
                                if (etx <= 258) {
                                    return 58702;
                                } else {
                                    return 47131;
                                }
                            } else {
                                return 33628;
                            }
                        }
                    }
                } else {
                    if (is_new <= 0) {
                        if (cpu <= 10) {
                            return 8902;
                        } else {
                            return 329;
                        }
                    } else {
                        if (nbr_count <= 7) {
                            if (etx <= 404) {
                                return 3715;
                            } else {
                                return 24061;
                            }
                        } else {
                            if (cpu <= 19) {
                                return 47279;
                            } else {
                                return 22402;
                            }
                        }
                    }
                }
            } else {
                if (rssi <= -52) {
                    if (ppm <= 760) {
                        if (parent_ppm <= 1659) {
                            return 12495;
                        } else {
                            if (hop_count <= 4) {
                                return 8270;
                            } else {
                                return 203;
                            }
                        }
                    } else {
                        if (parent_drop_rate <= 8) {
                            return 88;
                        } else {
                            return 3310;
                        }
                    }
                } else {
                    return 21509;
                }
            }
        } else {
            if (parent_drop_rate <= 0) {
                if (hop_count <= 52) {
                    if (ppm <= 82) {
                        if (ppm <= 26) {
                            if (etx <= 236) {
                                if (is_new <= 0) {
                                    if (etx <= 211) {
                                        return 20743;
                                    } else {
                                        return 29868;
                                    }
                                } else {
                                    if (hop_count <= 17) {
                                        if (cpu <= 48) {
                                            return 32181;
                                        } else {
                                            return 7841;
                                        }
                                    } else {
                                        return 1223;
                                    }
                                }
                            } else {
                                if (is_new <= 0) {
                                    if (hop_count <= 11) {
                                        return 3025;
                                    } else {
                                        return 15936;
                                    }
                                } else {
                                    if (p_cpu <= 76) {
                                        return 223;
                                    } else {
                                        if (etx <= 292) {
                                            return 6337;
                                        } else {
                                            return 2033;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (hop_count <= 15) {
                                if (rssi <= -78) {
                                    if (hop_count <= 8) {
                                        return 21976;
                                    } else {
                                        if (rssi <= -85) {
                                            return 42694;
                                        } else {
                                            return 62382;
                                        }
                                    }
                                } else {
                                    if (etx <= 188) {
                                        return 38018;
                                    } else {
                                        if (nbr_count <= 7) {
                                            return 15576;
                                        } else {
                                            return 30827;
                                        }
                                    }
                                }
                            } else {
                                if (ppm <= 53) {
                                    if (rssi <= -81) {
                                        if (nbr_count <= 5) {
                                            return 48907;
                                        } else {
                                            return 30957;
                                        }
                                    } else {
                                        if (p_cpu <= 57) {
                                            return 12344;
                                        } else {
                                            return 26300;
                                        }
                                    }
                                } else {
                                    if (rssi <= -79) {
                                        if (nbr_count <= 6) {
                                            return 2569;
                                        } else {
                                            return 13564;
                                        }
                                    } else {
                                        if (p_cpu <= 34) {
                                            return 1759;
                                        } else {
                                            return 19156;
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        if (hop_count <= 38) {
                            if (hop_count <= 11) {
                                if (nbr_count <= 7) {
                                    if (cpu <= 2) {
                                        if (ppm <= 108) {
                                            return 14782;
                                        } else {
                                            return 2589;
                                        }
                                    } else {
                                        if (etx <= 184) {
                                            return 8019;
                                        } else {
                                            return 16335;
                                        }
                                    }
                                } else {
                                    if (parent_ppm <= 111) {
                                        if (parent_ppm <= 18) {
                                            return 33433;
                                        } else {
                                            return 52048;
                                        }
                                    } else {
                                        if (p_cpu <= 26) {
                                            return 7605;
                                        } else {
                                            return 24288;
                                        }
                                    }
                                }
                            } else {
                                if (ppm <= 953) {
                                    if (rssi <= -75) {
                                        if (rssi <= -76) {
                                            return 12042;
                                        } else {
                                            return 36123;
                                        }
                                    } else {
                                        if (p_cpu <= 114) {
                                            return 7880;
                                        } else {
                                            return 22607;
                                        }
                                    }
                                } else {
                                    if (rssi <= -52) {
                                        if (p_cpu <= 119) {
                                            return 4097;
                                        } else {
                                            return 11968;
                                        }
                                    } else {
                                        if (rssi <= -48) {
                                            return 19573;
                                        } else {
                                            return 6156;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (hop_count <= 43) {
                                if (rssi <= -51) {
                                    if (nbr_count <= 7) {
                                        if (etx <= 280) {
                                            return 36659;
                                        } else {
                                            return 6135;
                                        }
                                    } else {
                                        return 55753;
                                    }
                                } else {
                                    if (hop_count <= 41) {
                                        return 18502;
                                    } else {
                                        return 5089;
                                    }
                                }
                            } else {
                                if (nbr_count <= 4) {
                                    if (rssi <= -59) {
                                        return 7049;
                                    } else {
                                        return 182;
                                    }
                                } else {
                                    if (parent_ppm <= 1755) {
                                        if (ppm <= 1639) {
                                            return 22739;
                                        } else {
                                            return 6757;
                                        }
                                    } else {
                                        return 778;
                                    }
                                }
                            }
                        }
                    }
                } else {
                    if (hop_count <= 75) {
                        if (parent_ppm <= 57) {
                            if (cpu <= 29) {
                                return 23137;
                            } else {
                                if (rssi <= -61) {
                                    return 1266;
                                } else {
                                    return 13539;
                                }
                            }
                        } else {
                            if (ppm <= 107) {
                                if (nbr_count <= 7) {
                                    if (ppm <= 87) {
                                        if (nbr_count <= 6) {
                                            return 2070;
                                        } else {
                                            return 7194;
                                        }
                                    } else {
                                        return 16804;
                                    }
                                } else {
                                    return 18566;
                                }
                            } else {
                                if (hop_count <= 61) {
                                    if (etx <= 159) {
                                        return 12501;
                                    } else {
                                        if (rssi <= -44) {
                                            return 3201;
                                        } else {
                                            return 9832;
                                        }
                                    }
                                } else {
                                    if (rssi <= -71) {
                                        if (rssi <= -75) {
                                            return 0;
                                        } else {
                                            return 14921;
                                        }
                                    } else {
                                        if (etx <= 298) {
                                            return 223;
                                        } else {
                                            return 5064;
                                        }
                                    }
                                }
                            }
                        }
                    } else {
                        if (p_cpu <= 109) {
                            if (cpu <= 21) {
                                if (etx <= 219) {
                                    return 14644;
                                } else {
                                    return 31054;
                                }
                            } else {
                                return 9268;
                            }
                        } else {
                            if (ppm <= 980) {
                                if (p_cpu <= 119) {
                                    return 6713;
                                } else {
                                    return 0;
                                }
                            } else {
                                return 14672;
                            }
                        }
                    }
                }
            } else {
                if (parent_ppm <= 1105) {
                    if (parent_drop_rate <= 3) {
                        if (etx <= 373) {
                            if (cpu <= 4) {
                                if (nbr_count <= 6) {
                                    return 1768;
                                } else {
                                    return 11861;
                                }
                            } else {
                                if (cpu <= 121) {
                                    if (p_cpu <= 119) {
                                        if (p_cpu <= 106) {
                                            return 0;
                                        } else {
                                            return 1043;
                                        }
                                    } else {
                                        return 2477;
                                    }
                                } else {
                                    return 6469;
                                }
                            }
                        } else {
                            return 12436;
                        }
                    } else {
                        if (nbr_count <= 6) {
                            if (rssi <= -70) {
                                if (ppm <= 317) {
                                    return 596;
                                } else {
                                    return 0;
                                }
                            } else {
                                if (cpu <= 12) {
                                    return 16527;
                                } else {
                                    return 4310;
                                }
                            }
                        } else {
                            if (p_cpu <= 97) {
                                if (p_cpu <= 50) {
                                    if (p_cpu <= 43) {
                                        return 9557;
                                    } else {
                                        return 42474;
                                    }
                                } else {
                                    if (parent_drop_rate <= 29) {
                                        if (cpu <= 33) {
                                            return 114;
                                        } else {
                                            return 5461;
                                        }
                                    } else {
                                        return 15640;
                                    }
                                }
                            } else {
                                if (ppm <= 726) {
                                    return 46230;
                                } else {
                                    return 18478;
                                }
                            }
                        }
                    }
                } else {
                    if (etx <= 319) {
                        if (parent_drop_rate <= 6) {
                            if (hop_count <= 24) {
                                if (etx <= 153) {
                                    return 4571;
                                } else {
                                    if (ppm <= 49) {
                                        return 4103;
                                    } else {
                                        if (p_cpu <= 31) {
                                            return 1034;
                                        } else {
                                            return 165;
                                        }
                                    }
                                }
                            } else {
                                if (is_new <= 0) {
                                    if (parent_ppm <= 1799) {
                                        if (nbr_count <= 6) {
                                            return 0;
                                        } else {
                                            return 8264;
                                        }
                                    } else {
                                        if (cpu <= 67) {
                                            return 0;
                                        } else {
                                            return 1229;
                                        }
                                    }
                                } else {
                                    if (nbr_count <= 6) {
                                        return 16859;
                                    } else {
                                        if (cpu <= 37) {
                                            return 4371;
                                        } else {
                                            return 30;
                                        }
                                    }
                                }
                            }
                        } else {
                            if (cpu <= 13) {
                                if (parent_ppm <= 1978) {
                                    if (ppm <= 84) {
                                        return 25750;
                                    } else {
                                        if (cpu <= 4) {
                                            return 4247;
                                        } else {
                                            return 16092;
                                        }
                                    }
                                } else {
                                    if (ppm <= 125) {
                                        if (rssi <= -64) {
                                            return 197;
                                        } else {
                                            return 4990;
                                        }
                                    } else {
                                        if (nbr_count <= 6) {
                                            return 4437;
                                        } else {
                                            return 13770;
                                        }
                                    }
                                }
                            } else {
                                if (parent_drop_rate <= 114) {
                                    if (rssi <= -55) {
                                        if (nbr_count <= 5) {
                                            return 287;
                                        } else {
                                            return 2601;
                                        }
                                    } else {
                                        if (hop_count <= 19) {
                                            return 8640;
                                        } else {
                                            return 397;
                                        }
                                    }
                                } else {
                                    if (p_cpu <= 61) {
                                        return 16640;
                                    } else {
                                        return 5325;
                                    }
                                }
                            }
                        }
                    } else {
                        if (p_cpu <= 118) {
                            if (p_cpu <= 55) {
                                if (etx <= 386) {
                                    return 11909;
                                } else {
                                    return 27138;
                                }
                            } else {
                                if (ppm <= 544) {
                                    if (parent_drop_rate <= 4) {
                                        return 8214;
                                    } else {
                                        return 1465;
                                    }
                                } else {
                                    if (hop_count <= 25) {
                                        return 0;
                                    } else {
                                        return 473;
                                    }
                                }
                            }
                        } else {
                            return 27262;
                        }
                    }
                }
            }
        }
    }
}
