/* Auto-generated by scripts/models/to_c.py (linear) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead.
 */
#ifndef MLOF_PREDICT_PDR_LINEAR_H_
#define MLOF_PREDICT_PDR_LINEAR_H_
#include <stdint.h>

uint16_t mlof_predict_pdr_linear(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count);

#endif /* MLOF_PREDICT_PDR_LINEAR_H_ */
