/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-linear.h"

static void mlof_predict_pdr_linear_standardise(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count, int32_t *out) {
    out[0] = ((int32_t)is_new - 0L) * 213L;
    out[1] = ((int32_t)cpu - 19L) * 5L;
    out[2] = ((int32_t)p_cpu - 22L) * 5L;
    out[3] = ((int32_t)drop_rate - 3L) * 12L;
    out[4] = ((int32_t)parent_ppm - 234L) * 1L;
    out[5] = ((int32_t)hop_count - 5L) * 19L;
}

uint16_t mlof_predict_pdr_linear(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    int32_t z[6];
    mlof_predict_pdr_linear_standardise(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count, z);
    int32_t sum = 4764509L;
    sum += -3463L * z[0];
    sum += -1903L * z[1];
    sum += -8769L * z[2];
    sum += -2033L * z[3];
    sum += -678L * z[4];
    sum += -7921L * z[5];
    int32_t result = sum / 100L;
    if (result < 0) result = 0;
    if (result > 65535) result = 65535;
    return (uint16_t)result;
}
