/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-linear.h"

uint16_t mlof_predict_pdr_linear(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count) {
    int32_t sum = 5469973;
    sum += -456 * (int32_t)parent_ppm;
    sum += 7751 * (int32_t)parent_drop_rate;
    sum += 117 * (int32_t)rssi;
    sum += -31082 * (int32_t)hop_count;
    sum += -328449 * (int32_t)is_new;
    sum += 31 * (int32_t)cpu;
    sum += -24345 * (int32_t)p_cpu;
    sum += -2935 * (int32_t)etx;
    sum += -281 * (int32_t)ppm;
    sum += 1773 * (int32_t)drop_rate;
    sum += 65890 * (int32_t)nbr_count;
    int32_t result = sum / 100;
    if (result < 0) result = 0;
    if (result > 65535) result = 65535;
    return (uint16_t)result;
}
