/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-svm.h"

uint16_t mlof_predict_pdr_svm(uint16_t parent_ppm, uint8_t parent_drop_rate, int16_t rssi, uint8_t hop_count, uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, uint16_t ppm, uint8_t drop_rate, uint8_t nbr_count) {
    int32_t sum = 5532718;
    sum += -628 * (int32_t)parent_ppm;
    sum += 10558 * (int32_t)parent_drop_rate;
    sum += 1684 * (int32_t)rssi;
    sum += -33769 * (int32_t)hop_count;
    sum += -490517 * (int32_t)is_new;
    sum += 690 * (int32_t)cpu;
    sum += -29110 * (int32_t)p_cpu;
    sum += -3045 * (int32_t)etx;
    sum += -300 * (int32_t)ppm;
    sum += 2325 * (int32_t)drop_rate;
    sum += 58588 * (int32_t)nbr_count;
    int32_t result = sum / 100;
    if (result < 0) result = 0;
    if (result > 65535) result = 65535;
    return (uint16_t)result;
}
