/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double) from a trained model.
 * DO NOT EDIT BY HAND -- retrain and re-run the converter instead. */
#include "mlof-lgbm.h"

static int32_t mlof_predict_pdr_lgbm_tree0(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 28) {
            if (is_new <= 0) {
                return 49286;
            } else {
                if (hop_count <= 3) {
                    return 48840;
                } else {
                    return 47172;
                }
            }
        } else {
            return 46520;
        }
    } else {
        if (p_cpu <= 28) {
            if (p_cpu <= 15) {
                return 47244;
            } else {
                return 45731;
            }
        } else {
            return 44709;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree1(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 28) {
            if (is_new <= 0) {
                return 1479;
            } else {
                if (hop_count <= 2) {
                    return 1234;
                } else {
                    return -81;
                }
            }
        } else {
            return -977;
        }
    } else {
        if (p_cpu <= 32) {
            if (p_cpu <= 15) {
                return -332;
            } else {
                return -1828;
            }
        } else {
            return -2707;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree2(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 23) {
        if (is_new <= 0) {
            return 1249;
        } else {
            if (p_cpu <= 13) {
                return 785;
            } else {
                return -1143;
            }
        }
    } else {
        if (drop_rate <= 2) {
            if (p_cpu <= 32) {
                if (is_new <= 0) {
                    return -218;
                } else {
                    return -1646;
                }
            } else {
                return -2011;
            }
        } else {
            return -2835;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree3(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 23) {
        if (is_new <= 0) {
            if (p_cpu <= 15) {
                return 1216;
            } else {
                return 633;
            }
        } else {
            if (p_cpu <= 10) {
                return 869;
            } else {
                return -857;
            }
        }
    } else {
        if (drop_rate <= 2) {
            if (p_cpu <= 35) {
                return -874;
            } else {
                return -1877;
            }
        } else {
            return -2582;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree4(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 30) {
            return 1045;
        } else {
            if (is_new <= 0) {
                return 399;
            } else {
                return -1525;
            }
        }
    } else {
        if (drop_rate <= 0) {
            if (hop_count <= 7) {
                if (p_cpu <= 20) {
                    return 396;
                } else {
                    return -1021;
                }
            } else {
                return -1606;
            }
        } else {
            return -2283;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree5(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (p_cpu <= 30) {
            if (is_new <= 0) {
                return 996;
            } else {
                return 510;
            }
        } else {
            return -656;
        }
    } else {
        if (drop_rate <= 2) {
            if (p_cpu <= 20) {
                if (hop_count <= 9) {
                    return 31;
                } else {
                    return -1387;
                }
            } else {
                return -1468;
            }
        } else {
            return -2147;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree6(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 21) {
        if (is_new <= 0) {
            return 846;
        } else {
            if (p_cpu <= 8) {
                return 734;
            } else {
                return -449;
            }
        }
    } else {
        if (p_cpu <= 35) {
            if (is_new <= 0) {
                return -256;
            } else {
                return -1288;
            }
        } else {
            if (drop_rate <= 1) {
                return -1348;
            } else {
                return -1958;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree7(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 4) {
            return 798;
        } else {
            if (is_new <= 0) {
                return 358;
            } else {
                return -1083;
            }
        }
    } else {
        if (drop_rate <= 0) {
            if (hop_count <= 7) {
                return -366;
            } else {
                return -1196;
            }
        } else {
            if (cpu <= 28) {
                return -1420;
            } else {
                return -1917;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree8(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 20) {
        if (is_new <= 0) {
            return 703;
        } else {
            if (p_cpu <= 8) {
                return 586;
            } else {
                return -333;
            }
        }
    } else {
        if (p_cpu <= 35) {
            if (is_new <= 0) {
                return -123;
            } else {
                return -1021;
            }
        } else {
            if (drop_rate <= 1) {
                return -1114;
            } else {
                return -1614;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree9(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 3) {
            return 694;
        } else {
            if (drop_rate <= 0) {
                return 386;
            } else {
                return -1227;
            }
        }
    } else {
        if (cpu <= 31) {
            if (hop_count <= 6) {
                return -116;
            } else {
                if (drop_rate <= 5) {
                    return -881;
                } else {
                    return -1398;
                }
            }
        } else {
            return -1450;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree10(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 3) {
            return 630;
        } else {
            if (is_new <= 0) {
                return 413;
            } else {
                return -638;
            }
        }
    } else {
        if (cpu <= 39) {
            if (hop_count <= 7) {
                return -322;
            } else {
                if (p_cpu <= 56) {
                    return -845;
                } else {
                    return -1326;
                }
            }
        } else {
            return -1409;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree11(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 4) {
            return 536;
        } else {
            if (cpu <= 35) {
                return 114;
            } else {
                return -1411;
            }
        }
    } else {
        if (drop_rate <= 0) {
            if (hop_count <= 8) {
                if (p_cpu <= 43) {
                    return -96;
                } else {
                    return -879;
                }
            } else {
                return -848;
            }
        } else {
            return -1179;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree12(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (cpu <= 58) {
            if (hop_count <= 4) {
                return 496;
            } else {
                return -6;
            }
        } else {
            if (hop_count <= 2) {
                return 323;
            } else {
                return -1486;
            }
        }
    } else {
        if (cpu <= 29) {
            if (hop_count <= 7) {
                return -128;
            } else {
                return -722;
            }
        } else {
            return -1063;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree13(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (hop_count <= 3) {
            return 461;
        } else {
            if (drop_rate <= 1) {
                return 253;
            } else {
                return -1110;
            }
        }
    } else {
        if (cpu <= 40) {
            if (hop_count <= 6) {
                return 43;
            } else {
                if (drop_rate <= 8) {
                    return -583;
                } else {
                    return -1048;
                }
            }
        } else {
            return -1054;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree14(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 26) {
        if (p_cpu <= 15) {
            return 386;
        } else {
            if (is_new <= 0) {
                return 188;
            } else {
                return -531;
            }
        }
    } else {
        if (parent_ppm <= 233) {
            return -1061;
        } else {
            if (p_cpu <= 49) {
                if (drop_rate <= 8) {
                    return -241;
                } else {
                    return -826;
                }
            } else {
                return -802;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree15(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (p_cpu <= 40) {
            if (drop_rate <= 2) {
                return 362;
            } else {
                if (hop_count <= 2) {
                    return 329;
                } else {
                    return -785;
                }
            }
        } else {
            return -667;
        }
    } else {
        if (drop_rate <= 8) {
            if (cpu <= 51) {
                return -480;
            } else {
                return -900;
            }
        } else {
            return -970;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree16(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 5) {
        if (cpu <= 58) {
            return 315;
        } else {
            if (hop_count <= 2) {
                return 148;
            } else {
                return -1226;
            }
        }
    } else {
        if (drop_rate <= 4) {
            if (parent_ppm <= 135) {
                return -966;
            } else {
                if (p_cpu <= 56) {
                    return -319;
                } else {
                    return -702;
                }
            }
        } else {
            return -791;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree17(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        return 294;
    } else {
        if (p_cpu <= 15) {
            if (hop_count <= 9) {
                return 318;
            } else {
                return -682;
            }
        } else {
            if (parent_ppm <= 235) {
                return -839;
            } else {
                if (p_cpu <= 51) {
                    if (parent_ppm <= 893) {
                        return -267;
                    } else {
                        return -1271;
                    }
                } else {
                    return -609;
                }
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree18(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        return 266;
    } else {
        if (drop_rate <= 0) {
            if (parent_ppm <= 701) {
                if (hop_count <= 7) {
                    return 71;
                } else {
                    if (parent_ppm <= 284) {
                        return -571;
                    } else {
                        return -143;
                    }
                }
            } else {
                return -871;
            }
        } else {
            if (parent_ppm <= 301) {
                return -902;
            } else {
                return -459;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree19(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (cpu <= 76) {
            return 247;
        } else {
            return -691;
        }
    } else {
        if (cpu <= 25) {
            if (hop_count <= 7) {
                if (p_cpu <= 41) {
                    return 167;
                } else {
                    return -451;
                }
            } else {
                return -324;
            }
        } else {
            if (parent_ppm <= 284) {
                return -828;
            } else {
                return -406;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree20(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (is_new <= 0) {
            return 235;
        } else {
            if (hop_count <= 2) {
                return 204;
            } else {
                if (parent_ppm <= 181) {
                    return -810;
                } else {
                    return -161;
                }
            }
        }
    } else {
        if (parent_ppm <= 181) {
            return -719;
        } else {
            if (p_cpu <= 56) {
                return -259;
            } else {
                return -553;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree21(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (hop_count <= 2) {
            return 241;
        } else {
            return 90;
        }
    } else {
        if (drop_rate <= 8) {
            if (p_cpu <= 15) {
                return 161;
            } else {
                if (parent_ppm <= 133) {
                    return -1014;
                } else {
                    if (parent_ppm <= 893) {
                        return -203;
                    } else {
                        return -1015;
                    }
                }
            }
        } else {
            return -603;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree22(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (is_new <= 0) {
            return 194;
        } else {
            if (hop_count <= 2) {
                return 183;
            } else {
                if (parent_ppm <= 181) {
                    return -721;
                } else {
                    return -124;
                }
            }
        }
    } else {
        if (parent_ppm <= 135) {
            return -784;
        } else {
            if (p_cpu <= 56) {
                return -222;
            } else {
                return -477;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree23(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 6) {
        if (cpu <= 47) {
            return 159;
        } else {
            if (hop_count <= 2) {
                return 97;
            } else {
                return -741;
            }
        }
    } else {
        if (parent_ppm <= 241) {
            if (cpu <= 23) {
                return -289;
            } else {
                return -692;
            }
        } else {
            if (drop_rate <= 8) {
                return -146;
            } else {
                return -432;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree24(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        return 144;
    } else {
        if (cpu <= 45) {
            if (hop_count <= 8) {
                if (drop_rate <= 7) {
                    return 52;
                } else {
                    return -384;
                }
            } else {
                if (parent_ppm <= 738) {
                    if (parent_ppm <= 284) {
                        return -368;
                    } else {
                        return -125;
                    }
                } else {
                    return -615;
                }
            }
        } else {
            return -485;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree25(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 4) {
        if (cpu <= 58) {
            return 135;
        } else {
            if (hop_count <= 1) {
                return 180;
            } else {
                return -904;
            }
        }
    } else {
        if (p_cpu <= 15) {
            return 164;
        } else {
            if (cpu <= 39) {
                if (p_cpu <= 62) {
                    return -139;
                } else {
                    return -460;
                }
            } else {
                return -403;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree26(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (p_cpu <= 23) {
            return 121;
        } else {
            return 553;
        }
    } else {
        if (drop_rate <= 0) {
            if (parent_ppm <= 738) {
                if (hop_count <= 10) {
                    return 56;
                } else {
                    return -189;
                }
            } else {
                return -637;
            }
        } else {
            if (parent_ppm <= 296) {
                return -595;
            } else {
                return -199;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree27(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 7) {
        if (cpu <= 63) {
            if (drop_rate <= 0) {
                return 118;
            } else {
                return -117;
            }
        } else {
            return -422;
        }
    } else {
        if (parent_ppm <= 284) {
            return -349;
        } else {
            if (drop_rate <= 11) {
                if (parent_ppm <= 562) {
                    return 18;
                } else {
                    return -290;
                }
            } else {
                return -365;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree28(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (drop_rate <= 0) {
        if (parent_ppm <= 681) {
            if (cpu <= 55) {
                if (p_cpu <= 44) {
                    return 101;
                } else {
                    return -117;
                }
            } else {
                return -261;
            }
        } else {
            return -460;
        }
    } else {
        if (parent_ppm <= 396) {
            if (p_cpu <= 6) {
                return 81;
            } else {
                return -392;
            }
        } else {
            return -94;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree29(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 3) {
        if (p_cpu <= 23) {
            return 91;
        } else {
            return 487;
        }
    } else {
        if (drop_rate <= 0) {
            if (parent_ppm <= 893) {
                if (hop_count <= 20) {
                    return 4;
                } else {
                    return -580;
                }
            } else {
                return -731;
            }
        } else {
            if (parent_ppm <= 235) {
                return -583;
            } else {
                return -165;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree30(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (p_cpu <= 18) {
        return 74;
    } else {
        if (parent_ppm <= 181) {
            if (is_new <= 0) {
                return -130;
            } else {
                return -574;
            }
        } else {
            if (p_cpu <= 59) {
                if (drop_rate <= 5) {
                    if (parent_ppm <= 963) {
                        return 34;
                    } else {
                        return -874;
                    }
                } else {
                    return -219;
                }
            } else {
                return -282;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree31(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 7) {
        if (cpu <= 64) {
            if (p_cpu <= 44) {
                return 80;
            } else {
                return -256;
            }
        } else {
            if (hop_count <= 1) {
                return 260;
            } else {
                if (parent_ppm <= 317) {
                    return -856;
                } else {
                    return -79;
                }
            }
        }
    } else {
        if (parent_ppm <= 135) {
            return -539;
        } else {
            return -127;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree32(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 2) {
        return 102;
    } else {
        if (cpu <= 29) {
            if (parent_ppm <= 562) {
                if (parent_ppm <= 105) {
                    if (is_new <= 0) {
                        return -102;
                    } else {
                        return -708;
                    }
                } else {
                    return 66;
                }
            } else {
                return -244;
            }
        } else {
            if (parent_ppm <= 187) {
                return -480;
            } else {
                return -140;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree33(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 2) {
        return 90;
    } else {
        if (cpu <= 41) {
            if (parent_ppm <= 927) {
                if (drop_rate <= 11) {
                    if (parent_ppm <= 91) {
                        return -153;
                    } else {
                        return 30;
                    }
                } else {
                    return -241;
                }
            } else {
                return -520;
            }
        } else {
            if (parent_ppm <= 219) {
                return -495;
            } else {
                return -154;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree34(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 8) {
        if (drop_rate <= 7) {
            if (p_cpu <= 44) {
                if (parent_ppm <= 927) {
                    if (parent_ppm <= 105) {
                        return 13;
                    } else {
                        return 113;
                    }
                } else {
                    return -1217;
                }
            } else {
                if (parent_ppm <= 344) {
                    return -458;
                } else {
                    return 58;
                }
            }
        } else {
            return -178;
        }
    } else {
        return -132;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree35(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (drop_rate <= 0) {
        if (parent_ppm <= 691) {
            if (cpu <= 95) {
                return 45;
            } else {
                return -729;
            }
        } else {
            if (cpu <= 28) {
                return -490;
            } else {
                return 184;
            }
        }
    } else {
        if (parent_ppm <= 396) {
            if (cpu <= 0) {
                return 647;
            } else {
                return -219;
            }
        } else {
            return -17;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree36(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 2) {
        if (p_cpu <= 23) {
            return 62;
        } else {
            return 586;
        }
    } else {
        if (cpu <= 14) {
            if (parent_ppm <= 562) {
                if (parent_ppm <= 65) {
                    return -165;
                } else {
                    return 88;
                }
            } else {
                return -237;
            }
        } else {
            if (parent_ppm <= 320) {
                return -214;
            } else {
                return -35;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree37(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (cpu <= 58) {
        if (hop_count <= 8) {
            return 46;
        } else {
            if (parent_ppm <= 87) {
                return -797;
            } else {
                return -75;
            }
        }
    } else {
        if (hop_count <= 1) {
            return 189;
        } else {
            if (parent_ppm <= 317) {
                if (drop_rate <= 54) {
                    return -459;
                } else {
                    return 1042;
                }
            } else {
                return -119;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree38(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (cpu <= 58) {
        if (drop_rate <= 17) {
            if (parent_ppm <= 562) {
                return 40;
            } else {
                if (cpu <= 33) {
                    return -207;
                } else {
                    return 238;
                }
            }
        } else {
            return -202;
        }
    } else {
        if (parent_ppm <= 317) {
            if (p_cpu <= 4) {
                return 100;
            } else {
                return -417;
            }
        } else {
            return -67;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree39(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 20) {
        if (drop_rate <= 4) {
            if (cpu <= 81) {
                if (hop_count <= 10) {
                    return 47;
                } else {
                    return -61;
                }
            } else {
                return -362;
            }
        } else {
            return -115;
        }
    } else {
        if (p_cpu <= 56) {
            if (cpu <= 5) {
                return 675;
            } else {
                return -279;
            }
        } else {
            return -675;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree40(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (cpu <= 69) {
        if (drop_rate <= 8) {
            if (parent_ppm <= 681) {
                if (p_cpu <= 68) {
                    return 30;
                } else {
                    return -260;
                }
            } else {
                if (drop_rate <= 0) {
                    if (cpu <= 25) {
                        return -449;
                    } else {
                        return 117;
                    }
                } else {
                    return 259;
                }
            }
        } else {
            return -145;
        }
    } else {
        return -214;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree41(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 8) {
        if (cpu <= 64) {
            if (parent_ppm <= 393) {
                if (drop_rate <= 0) {
                    return 37;
                } else {
                    if (hop_count <= 2) {
                        return 72;
                    } else {
                        return -298;
                    }
                }
            } else {
                return 161;
            }
        } else {
            return -214;
        }
    } else {
        if (parent_ppm <= 83) {
            return -703;
        } else {
            return -68;
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree42(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 2) {
        if (p_cpu <= 28) {
            return 42;
        } else {
            return 926;
        }
    } else {
        if (parent_ppm <= 91) {
            if (is_new <= 0) {
                return -112;
            } else {
                return -643;
            }
        } else {
            if (drop_rate <= 8) {
                return 7;
            } else {
                if (p_cpu <= 22) {
                    return -564;
                } else {
                    return -103;
                }
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree43(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 1) {
        return 71;
    } else {
        if (parent_ppm <= 77) {
            if (is_new <= 0) {
                return -79;
            } else {
                return -455;
            }
        } else {
            if (hop_count <= 8) {
                if (drop_rate <= 1) {
                    return 55;
                } else {
                    return -90;
                }
            } else {
                if (parent_ppm <= 284) {
                    return -161;
                } else {
                    return -12;
                }
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree44(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 20) {
        if (parent_ppm <= 927) {
            if (hop_count <= 1) {
                return 67;
            } else {
                if (parent_ppm <= 97) {
                    if (is_new <= 0) {
                        return -61;
                    } else {
                        return -424;
                    }
                } else {
                    return 10;
                }
            }
        } else {
            if (p_cpu <= 65) {
                return -517;
            } else {
                return 237;
            }
        }
    } else {
        return -289;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree45(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 8) {
        if (cpu <= 57) {
            return 26;
        } else {
            return -149;
        }
    } else {
        if (p_cpu <= 24) {
            if (hop_count <= 11) {
                if (p_cpu <= 20) {
                    return 189;
                } else {
                    return -322;
                }
            } else {
                return -446;
            }
        } else {
            if (cpu <= 1) {
                return 204;
            } else {
                return -56;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree46(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (cpu <= 44) {
        if (parent_ppm <= 963) {
            if (p_cpu <= 70) {
                return 25;
            } else {
                if (is_new <= 0) {
                    return -1171;
                } else {
                    if (parent_ppm <= 672) {
                        return -257;
                    } else {
                        return 573;
                    }
                }
            }
        } else {
            if (is_new <= 0) {
                return -869;
            } else {
                return 52;
            }
        }
    } else {
        return -88;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree47(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 21) {
        if (hop_count <= 1) {
            return 55;
        } else {
            if (parent_ppm <= 71) {
                if (cpu <= 65) {
                    return -103;
                } else {
                    return -1084;
                }
            } else {
                if (drop_rate <= 0) {
                    return 17;
                } else {
                    if (parent_ppm <= 396) {
                        return -162;
                    } else {
                        return 49;
                    }
                }
            }
        }
    } else {
        return -325;
    }
}

static int32_t mlof_predict_pdr_lgbm_tree48(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 20) {
        return 8;
    } else {
        if (p_cpu <= 56) {
            if (p_cpu <= 29) {
                return -481;
            } else {
                if (drop_rate <= 0) {
                    return -34;
                } else {
                    if (drop_rate <= 2) {
                        return 1766;
                    } else {
                        return 305;
                    }
                }
            }
        } else {
            if (drop_rate <= 3) {
                return -786;
            } else {
                return -171;
            }
        }
    }
}

static int32_t mlof_predict_pdr_lgbm_tree49(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    if (hop_count <= 8) {
        if (cpu <= 67) {
            return 20;
        } else {
            if (hop_count <= 1) {
                return 232;
            } else {
                if (parent_ppm <= 69) {
                    return -1855;
                } else {
                    if (parent_ppm <= 457) {
                        return -399;
                    } else {
                        return 129;
                    }
                }
            }
        }
    } else {
        if (parent_ppm <= 45) {
            return -1618;
        } else {
            return -55;
        }
    }
}

uint16_t mlof_predict_pdr_lgbm(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint8_t drop_rate, uint16_t parent_ppm, uint8_t hop_count) {
    int32_t sum = 0;
    sum += mlof_predict_pdr_lgbm_tree0(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree1(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree2(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree3(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree4(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree5(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree6(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree7(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree8(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree9(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree10(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree11(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree12(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree13(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree14(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree15(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree16(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree17(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree18(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree19(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree20(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree21(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree22(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree23(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree24(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree25(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree26(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree27(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree28(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree29(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree30(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree31(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree32(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree33(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree34(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree35(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree36(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree37(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree38(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree39(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree40(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree41(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree42(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree43(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree44(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree45(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree46(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree47(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree48(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    sum += mlof_predict_pdr_lgbm_tree49(is_new, cpu, p_cpu, drop_rate, parent_ppm, hop_count);
    if (sum < 0) sum = 0;
    if (sum > 65535) sum = 65535;
    return (uint16_t)sum;
}
