/* Auto-generated by scripts/models/to_c.py (fixed-point, no float/double)
 * from a trained model. DO NOT EDIT BY HAND -- retrain and re-run the
 * converter instead.
 *
 * mlof_predict_pdr_svm() standardises its inputs (subtract mean, scale by the
 * inverse std, both as integers) before applying the linear model, matching
 * how the model was trained.
 */
#ifndef MLOF_PREDICT_PDR_SVM_H_
#define MLOF_PREDICT_PDR_SVM_H_
#include <stdint.h>

uint16_t mlof_predict_pdr_svm(uint8_t is_new, uint8_t cpu, uint8_t p_cpu, uint16_t etx, int16_t rssi, uint16_t ppm, uint8_t drop_rate, uint16_t parent_ppm, uint8_t parent_drop_rate, uint8_t hop_count);

#endif /* MLOF_PREDICT_PDR_SVM_H_ */
